environment:
  machine_user: test_user
  machine_pass: Pass@word1
  KITCHEN_YAML: .kitchen.appveyor.yml

# Do not build on tags (GitHub only)
skip_tags: true

#faster cloning
clone_depth: 1

# Install the latest nightly of ChefDK
install:
  - ps: iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project chefdk -channel stable
  - ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
  - ps: $PSVersionTable
  - c:\opscode\chefdk\bin\chef.bat exec ruby --version
  - ps: secedit /export /cfg $env:temp/export.cfg
  - ps: ((get-content $env:temp/export.cfg) -replace ('PasswordComplexity = 1', 'PasswordComplexity = 0')) | Out-File $env:temp/export.cfg
  - ps: ((get-content $env:temp/export.cfg) -replace ('MinimumPasswordLength = 8', 'MinimumPasswordLength = 0')) | Out-File $env:temp/export.cfg
  - ps: secedit /configure /db $env:windir/security/new.sdb /cfg $env:temp/export.cfg /areas SECURITYPOLICY
  - ps: net user /add $env:machine_user $env:machine_pass
  - ps: net localgroup administrators $env:machine_user /add

build_script:
  - ps: c:\opscode\chefdk\bin\chef.bat shell-init powershell | iex; cmd /c c:\opscode\chefdk\bin\chef.bat --version

test_script:
  - c:\opscode\chefdk\bin\cookstyle --version
  - c:\opscode\chefdk\bin\chef.bat exec foodcritic --version
  - c:\opscode\chefdk\bin\chef.bat exec rspec spec/
  - c:\opscode\chefdk\bin\chef.bat exec cookstyle --display-cop-names --extra-details
  - c:\opscode\chefdk\bin\chef.bat exec foodcritic .
  - c:\opscode\chefdk\bin\chef.bat exec kitchen verify

deploy: off

# version: "master-{build}"

# os: Windows Server 2012 R2
# platform:
  # - x64
# environment:
  # winrm_user: test_user
  # winrm_pass: Pass@word1
  # winrm_port: 5985
  # KITCHEN_YAML: c:\GitHub\winrm\.kitchen.appveyor.yml
  # SSL_CERT_FILE: c:\GitHub\winrm\certs.pem
  # user_password: Pass@word1
  # UNIT_AND_LINT: 1

  # matrix:
  # - ruby_version: "23"

# clone_folder: c:\GitHub\winrm
# clone_depth: 1

# install:
  # - ps: net user /add $env:machine_user $env:machine_pass
  # - ps: net localgroup administrators $env:machine_user /add
  # - ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
  # - ps: gem install bundler --quiet --no-ri --no-rdoc
  # - ps: |-
       # [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
  # - ps: Invoke-WebRequest -Uri http://curl.haxx.se/ca/cacert.pem -OutFile c:\projects\kitchen-machine\certs.pem
  # - ps: ruby --version
  # - ps: gem --version
  # - ps: bundler --version

# build_script:
  # - bundle install

# test_script:
  # - chef exec delivery local all